name: xpressatec
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  animated_tree_view: ^2.3.0
  audioplayers: ^6.5.1
  cloud_firestore: ^6.0.3
  dio: ^5.9.0
  firebase_core: ^4.2.0
  firebase_storage: ^13.0.3
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  
  flutter_chat_ui: ^2.9.1
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.2.1
  table_calendar: ^3.0.9
  get: ^4.7.2
  hive_flutter: ^1.1.0
  http: ^1.5.0
  intl: ^0.20.2
  mobile_scanner: ^5.1.1
  image_picker: ^1.1.2
  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  web_socket_channel: ^3.0.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_logo.png"


flutter:
  uses-material-design: true

  fonts:
    - family: Cocogoose
      fonts:
        - asset: assets/fonts/cocogoose-regular.ttf



  assets:
    - .env
    - assets/
    - assets/images/
    - assets/images/amarillo/
    - assets/images/azul/
    - assets/images/cafe/
    - assets/images/cafe/casa/
    - assets/images/cafe/escuela/
    - assets/images/morado/
    - assets/images/naranja/
    - assets/images/rojo/
    - assets/images/rojo/DÃ­as/
    - assets/images/rojo/Estaciones/
    - assets/images/rojo/Meses/
    - assets/images/rojo/Tiempos/
    - assets/images/rosa/
    - assets/images/rosa/alimentos/
    - assets/images/rosa/higiene_personal/
    - assets/images/rosa/objetos_del_hogar/
    - assets/images/rosa/objetos_personales/
    - assets/images/rosa/vestimenta/
    - assets/images/verde/
    - assets/images/icon/
